config/routes.rb
RottenMangoes::Application.routes.draw do
  

  

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace :admin do
    resources :users
  end

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  # scope :less_than_90, -> (duration){ where("runtime_in_minutes < ?", duration) }
  has_many :reviews
  mount_uploader :image, ImageUploader

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past

  def review_average
    reviews.sum(:rating_out_of_ten) / reviews.size unless reviews.empty?
  end

  scope :title, -> (term) { where("title LIKE ? OR director LIKE ?", "%#{term}%", "%#{term}%") }
  scope :less_than_90 ,-> { where("runtime_in_minutes < ?", 90)}
  scope :between_90_120 ,-> { where("runtime_in_minutes >= ? AND runtime_in_minutes <= ?", 90, 120)}
  scope :greater_than_120 ,-> { where("runtime_in_minutes > ?", 120)}

  protected

  def release_date_is_in_the_past
    if release_date.present? && release_date > Date.today
      errors.add(:release_date, "should be in the past")
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
    
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
  	@users = User.all.page(params[:page]).per(3)
    if !current_user || current_user.is_admin == false
      redirect_to movies_path, notice: "You are not an Admin"
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	@user.update(is_admin: true)
    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.deletion_email(@user).deliver_now
    @user.destroy
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    if params[:search_term] && !params[:search_term].empty?
        @movies = @movies.title(params[:search_term])
    else
      @movies
    end

    if params[:duration] && !params[:duration].empty?
      if params[:duration] == 'under 90'
        @movies = @movies.less_than_90
      end
      if params[:duration] == 'Over 120'
        @movies = @movies.greater_than_120
      end
       if params[:duration] == 'Between 90 and 120'
        @movies = @movies.between_90_120
      end
    else
      @movies
    end

  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
    	session[:user_id] = user.id
    	redirect_to movies_path, notice: "Welcome back, #{user.firstname}"
    else
    	flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to movies_path, notice: "Adios"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end 

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>All users</h1>
<%= paginate @users %>
<%@users.each do |user|%>
	<p><%= link_to user.full_name, admin_user_path(user)%> (<%= link_to "delete", admin_user_path(user), method: :delete, data: {confirm: "you sure?"} %>)</p>
<% end %>

app/views/admin/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  	<%= f.hidden_field "is_admin", :value => true%>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
<h3><%=@user.full_name%></h3>
<ul>
<li>email: <%= @user.email%></li>
<li>signed_up: <%= @user.created_at%></li>
</ul>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
    <% if current_user.is_admin == true %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>) | <%= link_to "Admin", admin_users_path %>
    <% else %>
    	Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.text_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "poster_image_url" %><br>
    <%= f.text_field "poster_image_url" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.file_field "image" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.image_url(:thumb).to_s), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %> | <%= movie.review_average %>/10</h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
  <hr>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>

<%= form_tag movies_path, method: 'get' do |f|%>
  <p>
  	Search:
    <%= text_field_tag 'search_term', params[:search_term] %>
  </p>
  <p>
  	Duration: 
  	<%= select_tag(:duration, options_for_select(["", "under 90", "Between 90 and 120", "Over 120"])) %>
  </p>
  <p>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>
<hr/>

<%= render "movie" %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.image_url), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: { confirm: "You sure?" } %>) | <%= @movie.review_average %>/10</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%=link_to review.user.full_name, user_path(review.user)%></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/session/new.html.erb
<h1>Log In</h1>
<%= form_tag session_path do %>
  <div>
    <%= label_tag "email" %><br/>
    <%= text_field_tag "email" %>
  </div>
  <div>
    <%= label_tag :password %><br/>
    <%= password_field_tag :password %>
  </div>
  <div><%= submit_tag "Log In" %></div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<%= link_to "back", movie_path %>
<h2><%= @user.full_name %></h2>
<h2><%= @user.email %></h2>
<h2>Reviews:</h2>
<% @user.reviews.each do |review| %>
	<p><%= review.text%></p>
<% end %>